# standard jekyll configuration

permalink: /news/:title/
pygments: true
exclude: ['Rakefile', 'README']
markdown: rdiscount

# configuration required for some pages

domain: barroncraft.com
title: Barron Minecraft
description: Epic Minecraft games built by the community, for the community
author: Nullreff
email: contact@barroncraft.com

# 3rd party apps integration

github: barroncraft
disqus: barroncraft 
