# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md']
markdown: rdiscount

# configuration required for some pages

domain: barroncraft.com
title: Barron Minecraft
author: Nullreff
email: nullreff@barroncraft.com


# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
    username: barroncraft

# disqus:
#   id: disqusid
