# standard jekyll configuration

permalink: /news/:title/
pygments: true
exclude: ['Rakefile', 'README']
markdown: rdiscount

# configuration required for some pages

domain: barroncraft.com
title: Barron Minecraft
description: Epic Minecraft games built by the community, for the community
author: Nullreff
email: contact@barroncraft.com


# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
    username: barroncraft

disqus:
    id: barroncraft 
