# standard jekyll configuration

permalink: pretty
pygments: true
exclude: ['Rakefile', 'README']
markdown: rdiscount

# configuration required for some pages

domain: barroncraft.com
title: Barron Minecraft
description: Community PvP Maps
author: Nullreff
email: nullreff@barroncraft.com


# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
    username: barroncraft

# disqus:
#   id: disqusid
